### ISSUE TITLE
Broken FGC mode

### ISSUE THREAD

**Issue by 7SlicesOfBread** [GrammyMoney/haybox-GRAMCTRL#3]
It seems executing this profile causes the gram slim smash to freeze. After viewing the behavior in dolphin's input viewer, I can only describe it as "frozen".

The following screenshot is how the input viewer stays stuck after initializing FGC mode. Also happens with FGCwasd.
![Screenshot 2024-10-29 185340](https://github.com/user-attachments/assets/8517fae6-d2f0-40fa-b0c1-038a04d72d52)

**Comment by 7SlicesOfBread** [comment]
Created a PR to fix the issue

**Comment by GrammyMoney** [comment]
Thank you for da fix my goat
